version: '3.7'
services:
  postgres:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow

  init:
    build: .
    depends_on:
      - postgres
    command: >
      bash -c "
        sleep 10 &&
        airflow db init &&
        airflow db upgrade &&
        airflow users create --username admin --password admin --firstname Peter --lastname Parker --email spiderman@superhero.org --role Admin
      "

  webserver:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    command: webserver

  scheduler:
    build: .
    depends_on:
      - postgres
      - webserver
    volumes:
      - ./dags:/opt/airflow/dags
    command: scheduler